name: Auto-status

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, ready_for_review, converted_to_draft, closed]

jobs:
  auto-status:
    # Pinned to Hexadian-Corporation/.github @ main 2026-05-23 (see Dependabot for bumps)
    uses: Hexadian-Corporation/.github/.github/workflows/auto-status-reusable.yml@82c6bd07bfbf95b123f19d6a0da0dede44976f68
    secrets:
      PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
