name: PR Title

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  pr-title:
    # Pinned to Hexadian-Corporation/.github @ main 2026-05-23 (see Dependabot for bumps)
    uses: Hexadian-Corporation/.github/.github/workflows/pr-title-reusable.yml@82c6bd07bfbf95b123f19d6a0da0dede44976f68
